routes/auth_routes.py
from flask import Flask, request, redirect, url_for, flash, render_template, Blueprint
from models import User
from flask_login import login_user, login_required, logout_user

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email = email).first()
        if user and user.check_password(password):
            login_user(user)
            if user.role == 'admin':
                return redirect(url_for('admin.admin_dashboard'))
            elif user.role == 'doctor':
                return redirect(url_for('doctor.doctor_dashboard'))
            elif user.role == 'patient':
                return redirect(url_for('patient.patient_dashboard'))
        else:
            flash('Invalid email or password.')
            return redirect(url_for('auth.login'))

    return render_template('login.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

routes/doctor_routes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash
from models import Doctor, Patient, Treatment, Appointment, Availability
from flask_login import login_required, current_user
from extensions import db
from datetime import datetime, date
from datetime import date as dt_date 

doctor_bp = Blueprint('doctor', __name__, url_prefix='/doctor')

@doctor_bp.route('/dashboard')
@login_required
def doctor_dashboard():
    doctor = Doctor.query.filter_by(user_id=current_user.user_id).first_or_404()
    patient = Patient.query.all()
    appointments = Appointment.query.filter_by(doctor_id=doctor.doctor_id).order_by(Appointment.date.desc(), Appointment.time.desc()).all()
    return render_template('doctor/dashboard.html', doctor = doctor, appointments = appointments, pats=patient)

@doctor_bp.route('/add_treatment/<int:appointment_id>', methods = ['POST', 'GET'])
@login_required
def add_treatment(appointment_id):
    appointment = Appointment.query.get_or_404(appointment_id)
    doctor = appointment.doctor 
    patient = appointment.patient

    if request.method == 'POST':
        ailment = request.form['ailment']
        prescription = request.form['prescription']
        notes = request.form['notes']

        treatment = Treatment(
            ailment = ailment,
            prescription = prescription,
            notes = notes,
            appointment_id = appointment_id
        )
        
        appointment.status = "Completed"
        db.session.add(treatment)
        db.session.commit()
        return redirect(url_for('doctor.doctor_dashboard'))
    return render_template('doctor/treatment.html', doctor = doctor, patient = patient, app = appointment)                  

@doctor_bp.route('/view_treatment/<int:appointment_id>')
@login_required
def view_treatment(appointment_id):
    appointment = Appointment.query.get_or_404(appointment_id)
    doctor = appointment.doctor
    patient = appointment.patient

    treatment = Treatment.query.filter_by(appointment_id = appointment_id).all()
    return render_template('doctor/view_treatment.html', doctor=doctor, patient=patient, app=appointment, treatment = treatment)

@doctor_bp.route('/patient_history/<int:patient_id>')
@login_required
def patient_history(patient_id):
    patient = Patient.query.get_or_404(patient_id)
    appointment = Appointment.query.filter_by(patient_id = patient_id).order_by(Appointment.date.desc()).all()

    return render_template('doctor/patient_history.html',patient=patient,appointment=appointment)


@doctor_bp.route('/<int:doctor_id>/set_availability', methods=['GET', 'POST'])
@login_required
def set_availability(doctor_id):
    doctor = Doctor.query.get_or_404(doctor_id)

    TIME_SLOTS = {
        "09:00": "11:00",
        "11:00": "13:00",
        "13:00": "15:00",
        "15:00": "17:00",
        "17:00": "19:00",
        "19:00": "21:00"
    }

    if request.method == 'POST':
        selected_date_str = request.form.get("date")
        selected_start = request.form.get("time")

        # Convert date string → Python date
        selected_date = datetime.strptime(selected_date_str, "%Y-%m-%d").date()

        # Convert string → Python time
        start_time_obj = datetime.strptime(selected_start, "%H:%M").time()
        end_time_obj = datetime.strptime(TIME_SLOTS[selected_start], "%H:%M").time()

        # Prevent duplicate slot
        exists = Availability.query.filter_by(
            doctor_id=doctor_id,
            date=selected_date,
            start_time=start_time_obj
        ).first()

        if exists:
            flash("This slot already exists!", "warning")
            return redirect(request.url)

        new_slot = Availability(
            doctor_id=doctor_id,
            date=selected_date,
            start_time=start_time_obj,
            end_time=end_time_obj
        )

        db.session.add(new_slot)
        db.session.commit()

        flash("Availability added!", "success")
        return redirect(request.url)

    slots = Availability.query.filter_by(doctor_id=doctor_id).all()

    return render_template(
        'doctor/set_availability.html',
        doctor=doctor,
        slots=slots,
        TIME_SLOTS=TIME_SLOTS,
        today=date.today().isoformat()
    )

@doctor_bp.route('/remove_slot/<int:slot_id>')
@login_required
def remove_slot(slot_id):
    slot = Availability.query.get_or_404(slot_id)
    db.session.delete(slot)
    db.session.commit()
    flash("Slot removed successfully!", "success")
    return redirect(url_for('doctor.set_availability', doctor_id=slot.doctor_id))

templates/doctor/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arogya - {{ doctor.doc_name }}</title>
</head>
<body>
    <h1>Welcome {{ doctor.doc_name }}</h1>

    <h3>Appointments :</h3>
    <table border="1">
        <tr>
            <th>Appointment ID</th>
            <th>Patient</th>
            <th>Date</th>
            <th>Time</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for app in appointments %}
            <tr>
                <td>{{ app.appointment_id }}</td>
                <td><a href="{{ url_for('doctor.patient_history', patient_id=app.patient.patient_id) }}">{{ app.patient.pat_name }}</a></td>
                <td>{{ app.date.strftime('%d-%m-%Y') }}</td>
                <td>{{ app.time.strftime('%H-%m') }}</td>
                <td>{{ app.status }}</td>
                {% if app.status == 'Completed' %}
                <td><a href="{{ url_for('doctor.view_treatment', appointment_id=app.appointment_id) }}">Treatment Details</a></td>
                {% else %}
                <td><a href="{{ url_for('doctor.add_treatment', appointment_id=app.appointment_id) }}">Add Treatment</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

    <h3>Patient list: </h3>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Age</th>
            <th>Contact Number</th>
        </tr>
        {% for pats in pats %}
        <tr>
            <td>{{ pats.patient_id }}</td>
            <td>{{ pats.pat_name }}</td>
            <td>{{ pats.gender }}</td>
            <td>{{ pats.dob }}</td>
            <td>{{ pats.age }}</td>
            <td>{{ pats.contact_num }}</td>
        </tr>
        {% endfor %}
    </table>

    <div>
        <h3><a href="{{ url_for('doctor.set_availability', doctor_id=doctor.doctor_id) }}">Availability</a></h3>
    </div>

    {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
    {% endif %}
</body>
</html>

templates/doctor/patient_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient History</title>
</head>
<body>
    <h3>{{patient.pat_name}}</h3>
    <table>
        <tr>
            <th>ID</th>
            <th>Doctor</th>
            <th>Date</th>
            <th>Time</th>
            <th>Status</th>
            <th>Treatment</th>
        </tr>
         {% for app in appointment %}
        <tr>
            <td>{{ app.appointment_id }}</td>
            <td>{{ app.doctor.doc_name}}</td>
            <td>{{ app.date.strftime('%d-%m-%Y') }}</td>
            <td>{{ app.time.strftime('%H:%M') }}</td>
            <td>{{ app.status }}</td>
            <td><a href="{{url_for('doctor.view_treatment', appointment_id = app.appointment_id)}}">Treatment Details</a></td>
        </tr>
        {%endfor%}
    </table>
</body>
</html>

templates/doctor/set_availability.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Set Availability</title>
</head>
<body>

<h3>Set Availability</h3>

<form method="POST">
  <label for="date">Select Date:</label>
  <input type="date" name="date" id="date" required min="{{ today }}">

  <h4>Select Time Slot:</h4>
  {% for start, label in TIME_SLOTS.items() %}
      <button type="submit" name="time" value="{{ start }}">{{ label }}</button><br><br>
  {% endfor %}
</form>

<hr>

<h4>Existing Slots</h4>

<table border="1" cellpadding="8">
  <tr>
    <th>Date</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Action</th>
  </tr>
  {% for slot in slots %}
    <tr>
    <td>{{ slot.date.strftime('%d-%m-%Y') }}</td>
    <td>{{ slot.start_time.strftime('%H:%m') }}</td>
    <td>{{ slot.end_time.strftime('%H:%m') }}</td>
    <td>
      <a href="{{ url_for('doctor.remove_slot', slot_id=slot.id) }}">Remove</a>
    </td>
  </tr>
  {% endfor %}
</table>

</body>
</html>

templates/doctor/treatment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treatment</title>
</head>
<body>
    <h1>Treatment</h1>
    <h3>Doctor : {{doctor.doc_name}}</h3>
    <h3>Patient : {{patient.pat_name}}</h3>
    <h3>Date : {{app.date}}</h3>
    <h3>Time : {{app.time}}</h3>
    <form action="{{url_for('doctor.add_treatment', appointment_id = app.appointment_id)}}" method="POST">
        <label for="ailment" name="ailment">Ailment</label>
        <input name="ailment" type="text" class="ailment" id="ailment" required/>
        <br>
        <label for="prescription" name="prescription">Prescription</label>
        <input name="prescription" type="text" class="prescription" id="prescription" required/>
        <br>
        <label for="notes" name="">Notes</label>
        <input name="notes" type="text" class="notes" id="notes" required/>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

templates/doctor/view_treatment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treatment Details</title>
</head>
<body>
    <h1>Treatment Details</h1>
    <h3>Doctor : {{doctor.doc_name}}</h3>
    <h3>Patient : {{patient.pat_name}}</h3>
    <h3>Date : {{app.date}}</h3>
    <h3>Time : {{app.time}}</h3>
    <table>
        <tr>
            <th>Ailment</th>
            <th>Prescription</th>
            <th>Notes</th>
        </tr>
        {%for tm in treatment%}
        <tr>
            <td>{{tm.ailment}}</td>
            <td>{{tm.prescription}}</td>
            <td>{{tm.notes}}</td>
        </tr>
        {%endfor%}
    </table>
</body>
</html>